/*
* Name: Arjun Ramsinghani
* Title: Secure Health Information System
* Course: CS 4331-001 -- Software Security
 */

package secure.health.information.system;

/**
 *
 * @author arams
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        askquestions = new javax.swing.JButton();
        testresults = new javax.swing.JButton();
        paybill = new javax.swing.JButton();
        requestrefills = new javax.swing.JButton();
        patientportallabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        askquestions.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        askquestions.setText("Ask Questions");
        askquestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                askquestionsActionPerformed(evt);
            }
        });

        testresults.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        testresults.setText("Test Results");
        testresults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testresultsActionPerformed(evt);
            }
        });

        paybill.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        paybill.setText("Pay Bill");
        paybill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybillActionPerformed(evt);
            }
        });

        requestrefills.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        requestrefills.setText("Request Refills");
        requestrefills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestrefillsActionPerformed(evt);
            }
        });

        patientportallabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        patientportallabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientportallabel.setText("Patient Portal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(askquestions, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addComponent(testresults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 521, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(requestrefills, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paybill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(370, 370, 370))
            .addGroup(layout.createSequentialGroup()
                .addGap(645, 645, 645)
                .addComponent(patientportallabel, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(patientportallabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(askquestions, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paybill, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestrefills, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testresults, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(242, 242, 242))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void askquestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_askquestionsActionPerformed
        // TODO add your handling code here:
        dispose();
        new Doctors().setVisible(true); // sends you to ask questions
    }//GEN-LAST:event_askquestionsActionPerformed

    private void paybillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybillActionPerformed
        // TODO add your handling code here:
        dispose();
        new PayBill().setVisible(true); // sends you to pay bill
    }//GEN-LAST:event_paybillActionPerformed

    private void testresultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testresultsActionPerformed
        // TODO add your handling code here:
        dispose();
        new TestResults().setVisible(true); // sends you to test results
    }//GEN-LAST:event_testresultsActionPerformed

    private void requestrefillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestrefillsActionPerformed
        // TODO add your handling code here:
        dispose();
        new RequestRefills().setVisible(true); // sends you to request refills
    }//GEN-LAST:event_requestrefillsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton askquestions;
    private javax.swing.JLabel patientportallabel;
    private javax.swing.JButton paybill;
    private javax.swing.JButton requestrefills;
    private javax.swing.JButton testresults;
    // End of variables declaration//GEN-END:variables
}
