/*
Name: Arjun Ramsinghani
Title: Secure Health Information System
Course: CS 4331-001 -- Software Security
 */
package secure.health.information.system;

import java.io.File;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;

/**
 *
 * @author arams
 */
public class RequestRefills extends javax.swing.JFrame {

    String key = "12345678"; // key for encription

    /**
     * Creates new form RequestRefills
     */
    public RequestRefills() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor. //
     * https://www.youtube.com/watch?v=LP7_DlIe670&list=PLFDH5bKmoNqxtOTzA4tjo-Exck6T2v7cG&index=25
     * https://www.youtube.com/watch?v=dsYKi0LzGX8
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refilllabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicationtable = new javax.swing.JTable();
        displaybutton = new javax.swing.JButton();
        submitbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        refilltable = new javax.swing.JTable();
        processbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        refilllabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        refilllabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refilllabel.setText("Refill your Medication");

        medicationtable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        medicationtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medication", "Dose", "Used for", "Refill"
            }
        ));
        medicationtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicationtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(medicationtable);

        displaybutton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        displaybutton.setText("Display");
        displaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybuttonActionPerformed(evt);
            }
        });

        submitbutton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        refilltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medication", "Dose", "Used for", "Refill"
            }
        ));
        refilltable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refilltableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(refilltable);

        processbutton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        processbutton.setText("Process");
        processbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(displaybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(307, 307, 307)
                        .addComponent(refilllabel, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(processbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(669, 669, 669)
                                .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refilllabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(displaybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(processbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int phoneAuthorize(String phonenum) {

        String comp;
        String filepath = "phonenumber.txt"; // get the file
        File file = new File(filepath);
        
        try {
            Scanner myReader = new Scanner(file); // read the file
            while (myReader.hasNextLine()) {
                comp = myReader.nextLine();
                String[] row = comp.split(","); // split the column
                if (row[0].equals(phonenum)) {
                    return 1; // 1 is approved 
                }
            }
            myReader.close(); // close the file
        }
        
        catch (FileNotFoundException e) {
            System.out.println("An error occurred."); // error statement to console
            e.printStackTrace();
        }

        return 0; // not authorized
    }

    private void displaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybuttonActionPerformed
        // TODO add your handling code here:
        
        // files
        String filepath1 = "medicationlist.txt";
        File file1 = new File(filepath1);
        String filepath2 = "medicationlistencrypted.txt";
        File file2 = new File(filepath2);
        String filepath3 = "phonenumber.txt";
        File file3 = new File(filepath3);
        String filepath4 = "phonenumberencrypted.txt";
        File file4 = new File(filepath4);

        try {
            FileInputStream is = new FileInputStream(file3); // get the regular file
            FileOutputStream os = new FileOutputStream(file4); // get the encrypted file

            FileReader fr = new FileReader(file3); // read the file
            BufferedReader br = new BufferedReader(fr);

            String comparephonenumber;
            comparephonenumber = JOptionPane.showInputDialog("Please enter your phone number: "); // ask the user to write phone number

            if (phoneAuthorize(comparephonenumber) == 1) { // if the number is correct

                try {
                    FileInputStream is1 = new FileInputStream(file1); // get the regular file
                    FileOutputStream os1 = new FileOutputStream(file2); // get the encrypted file

                    FileReader fr1 = new FileReader(file1);
                    BufferedReader br1 = new BufferedReader(fr1);

                    DefaultTableModel model = (DefaultTableModel) medicationtable.getModel(); // get the table
                    Object[] lines = br1.lines().toArray(); // write the lines of the file to an array

                    for (int i = 1; i < lines.length; i++) {
                        String[] row = lines[i].toString().split(","); // split the string
                        model.addRow(row); // add the row
                    }

                    DataEncryptionStandard.encrypt(key, is1, os1); // encrypt the file
                }
                
                catch (FileNotFoundException ex) {
                    Logger.getLogger(RequestRefills.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                catch (Exception ex) {
                    Logger.getLogger(RequestRefills.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            else {
                JOptionPane.showMessageDialog(this, "This is not the correct phone number please try again");
                dispose();
                new RequestRefills().setVisible(true);
            }
            
            DataEncryptionStandard.encrypt(key, is, os);

        }
        
        catch (FileNotFoundException ex) {
            Logger.getLogger(RequestRefills.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (Exception ex) {
            Logger.getLogger(RequestRefills.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_displaybuttonActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) refilltable.getModel(); // get table
        int index[] = refilltable.getSelectedRows();
        DefaultTableModel model2 = (DefaultTableModel) refilltable.getModel(); // get table
        
        // get files
        String filepath1 = "refilllist.txt";
        File file1 = new File(filepath1);
        String filepath2 = "refilllistencrypted.txt";
        File file2 = new File(filepath2);

        Object[] row = new Object[4];

        for (int i = 0; i < index.length; i++) {
            row[0] = refilltable.getValueAt(index[i], 0); // get the value at a certain row column
            row[1] = refilltable.getValueAt(index[i], 1); // get the value at a certain row column
            row[2] = refilltable.getValueAt(index[i], 2); // get the value at a certain row column
            row[3] = "Ordered"; // write new column
            model2.addRow(row); // add row
        }

        try {
            FileInputStream is1 = new FileInputStream(file1);
            FileOutputStream os1 = new FileOutputStream(file2);

            FileWriter fw = new FileWriter(file1, true); // write true to append
            BufferedWriter bw = new BufferedWriter(fw);

            for (int i = 0; i < index.length; i++) {
                model1.removeRow(index[i]);
                row[0] = refilltable.getValueAt(index[i], 0); // get the value at a certain row column
                row[1] = refilltable.getValueAt(index[i], 1); // get the value at a certain row column
                row[2] = refilltable.getValueAt(index[i], 2); // get the value at a certain row column
                row[3] = "Ordered"; // write new column
                model2.addRow(row); // add row
                bw.write(row[0] + "," + row[1] + "," + row[2] + "," + row[3]); // write row
                bw.newLine(); // write new line
            }

            DataEncryptionStandard.encrypt(key, is1, os1); // encrypt file

            bw.close();
            fw.close(); // close file
        }
        
        catch (IOException ex) {
            Logger.getLogger(RequestRefills.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (NoSuchAlgorithmException | NoSuchPaddingException ex) {
            Logger.getLogger(RequestRefills.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (Exception ex) {
            Logger.getLogger(RequestRefills.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();
        new RefillSubmit().setVisible(true);
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void processbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processbuttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) medicationtable.getModel();
        int index[] = medicationtable.getSelectedRows(); // all rows
        DefaultTableModel model2 = (DefaultTableModel) refilltable.getModel();
        medicationtable.selectAll();

        Object[] row = new Object[4];

        for (int i = 0; i < index.length; i++) {
            row[0] = medicationtable.getValueAt(index[i], 0); // get the value at a certain row column
            row[1] = medicationtable.getValueAt(index[i], 1); // get the value at a certain row column
            row[2] = medicationtable.getValueAt(index[i], 2); // get the value at a certain row column
            row[3] = "Processing"; // write new column
            model2.addRow(row); // add new row
        }
    }//GEN-LAST:event_processbuttonActionPerformed

    private void medicationtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicationtableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_medicationtableMouseClicked

    private void refilltableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refilltableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_refilltableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestRefills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestRefills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestRefills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestRefills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestRefills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton displaybutton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable medicationtable;
    private javax.swing.JButton processbutton;
    private javax.swing.JLabel refilllabel;
    private javax.swing.JTable refilltable;
    private javax.swing.JButton submitbutton;
    // End of variables declaration//GEN-END:variables
}
