/*
Name: Arjun Ramsinghani
Title: Secure Health Information System
Course: CS 4331-001 -- Software Security
 */
package secure.health.information.system;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arams
 */
public class TestResults extends javax.swing.JFrame {

    String key = "12345678"; // key for encription

    /**
     * Creates new form TestResults
     */
    public TestResults() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * https://www.youtube.com/watch?v=LP7_DlIe670&list=PLFDH5bKmoNqxtOTzA4tjo-Exck6T2v7cG&index=25
     * https://www.youtube.com/watch?v=dsYKi0LzGX8
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testresultlabel = new javax.swing.JLabel();
        jScrollPanetest = new javax.swing.JScrollPane();
        testresultstable = new javax.swing.JTable();
        displaybutton = new javax.swing.JButton();
        homebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        testresultlabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        testresultlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        testresultlabel.setText("Test Results");

        testresultstable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        testresultstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Test", "Result"
            }
        ));
        jScrollPanetest.setViewportView(testresultstable);

        displaybutton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        displaybutton.setText("Display");
        displaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybuttonActionPerformed(evt);
            }
        });

        homebutton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        homebutton.setText("Home");
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(738, 738, 738)
                        .addComponent(testresultlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(displaybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPanetest, javax.swing.GroupLayout.PREFERRED_SIZE, 1807, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testresultlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displaybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPanetest, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int phoneAuthorize(String phonenum) {

        String comp;
        String filepath = "phonenumber.txt"; // get the file
        File file = new File(filepath);
        
        try {
            Scanner myReader = new Scanner(file); // read the file
            while (myReader.hasNextLine()) {
                comp = myReader.nextLine();
                String[] row = comp.split(","); // split the column
                if (row[0].equals(phonenum)) {
                    return 1; // 1 is approved 
                }
            }
            myReader.close(); // close the file
        }
        
        catch (FileNotFoundException e) {
            System.out.println("An error occurred."); // error statement to console
            e.printStackTrace();
        }

        return 0; // not authorized
    }

    private void displaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybuttonActionPerformed
        // TODO add your handling code here:
        
        // get files
        String filepath1 = "testresults.txt";
        File file1 = new File(filepath1);
        String filepath2 = "testresultsencrypted.txt";
        File file2 = new File(filepath2);
        String filepath3 = "phonenumber.txt";
        File file3 = new File(filepath3);
        String filepath4 = "phonenumberencrypted.txt";
        File file4 = new File(filepath4);

        try {
            FileInputStream is = new FileInputStream(file3); // get the regular file
            FileOutputStream os = new FileOutputStream(file4); // get the encrypted file

            FileReader fr = new FileReader(file3); // read the file
            BufferedReader br = new BufferedReader(fr);

            String comparephonenumber;
            comparephonenumber = JOptionPane.showInputDialog("Please enter your phone number: "); // ask the user to write phone number

            if (phoneAuthorize(comparephonenumber) == 1) { // if the number is correct

                try {
                    FileInputStream is1 = new FileInputStream(file1); // get the regular file
                    FileOutputStream os1 = new FileOutputStream(file2); // get the encrypted file

                    FileReader fr1 = new FileReader(file1);
                    BufferedReader br1 = new BufferedReader(fr1);

                    DefaultTableModel model = (DefaultTableModel) testresultstable.getModel(); // get the table
                    Object[] lines = br1.lines().toArray(); // write the lines of the file to an array

                    for (int i = 1; i < lines.length; i++) {
                        String[] row = lines[i].toString().split(","); // split the string
                        model.addRow(row); // add the row
                    }

                    DataEncryptionStandard.encrypt(key, is1, os1); // encrypt file
                }
                
                catch (FileNotFoundException ex) {
                    Logger.getLogger(RequestRefills.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            else {
                JOptionPane.showMessageDialog(this, "This is not the correct phone number please try again");
                dispose();
                new TestResults().setVisible(true);
            }
            
            DataEncryptionStandard.encrypt(key, is, os);
        }
        
        catch (FileNotFoundException ex) {
            Logger.getLogger(TestResults.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch (Exception ex) {
            Logger.getLogger(TestResults.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_displaybuttonActionPerformed

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainWindow().setVisible(true);
    }//GEN-LAST:event_homebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton displaybutton;
    private javax.swing.JButton homebutton;
    private javax.swing.JScrollPane jScrollPanetest;
    private javax.swing.JLabel testresultlabel;
    private javax.swing.JTable testresultstable;
    // End of variables declaration//GEN-END:variables
}
